Dir.glob('lib/tasks/*.rake').each { |r| load r}

#TO-DO : comprobar que el siguiente codigo es funcional
require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << 'test'
end

desc "Run tests"
task :default => :test
